all: clean compile

compile: 200104004099_main.c
	@echo "-------------------------------------------"
	@echo "Compiling all files..."
	@gcc -o MWCp 200104004099_main.c -pthread

clean:
	@echo "-------------------------------------------"
	@echo "Removing files..."
	@rm -f *.o
	@rm -f MWCp
